### ISSUE TITLE
How can I use it to accept payments from my website?

### ISSUE THREAD

**Issue by mdhuzaifapatel** [Suyash99/QR-Payment#1]
PLease let me know.

**Comment by Suyash99** [comment]
@mdhuzaifapatel. Firstly, Thanks for the interest in the repo. The server is based on the package from NPM about UPI. As you can see the basic codes, I was planning to use the QR method by embedding the user data on it and rendering the QR code on the front-end. Hence the user will be able to recieve the payment through UPI App when scanned from QR Code scanner. Also, this is just a draft and the repo is still WIP.
